import { Skeleton_card } from "components";
import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="text-3xl font-extrabold text-indigo-500 dark:text-white sm:text-4xl pt-20 text-center">
					My App
				</h1>
				<Skeleton_card />
			</main>
		</div>
	);
}
