import Head from "next/head";
import React from "react";
import CardTemplate from "../components/card-template/card-template";
import { mockBaseTemplateProps } from "../components/card-template/card-template.mocks";

/**
 * This is the home page!
 * @return {JSX.Element}: the JSX Element for home page.
 */
export default function Home() {
  console.log(process.env.PRIVATE_KEY);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome</h1>
        <CardTemplate {...mockBaseTemplateProps.base}></CardTemplate>
      </main>
    </div>
  );
}
